name: Pull MatterQA Issues Daily

on:
  schedule:
    # Schedule the workflow to run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  pull_issues:
    runs-on: ubuntu-latest

    env:
      PERSONNEL_TOKEN: ${{ secrets.PERSONNEL_TOKEN }}
      CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread pandas oauth2client google-auth requests google-auth-oauthlib google-auth-httplib2 PyYAML PyGithub
      
      - name: Run Python script
        run: |
          python Matter_Issues_Pull/MatterQA_Issues_Pull.py
